// Develop a banking system. 
// To do that, first, create an object named “bankAccount” with the following fields: 
// “bankAccountID”, which is autogenerated 
// “accountNumber” “credentials”, which is an array with a username, password, and pin 
// “balance”, which is an amount of money 
// “createdAt”, which is a date

// Create an object which represents a user account and has the following fields: 
// “bankAccount”, which is an object from task 1 
// “debitCard”, which is a card number “firstName” “lastName” “birthDate” 
// “validID”, which is an array with a type of ID—passport or driver’s license—and the ID number 
// “address”

// Outside the objects, create functions that enable interaction with a user’s bank account: 
// “getBankAccountDetails”, which checks if the username and password are correct and shows the bank account details 
// “withdrawMoney”, which checks if the username and password are correct and enables getting money from the bank account using the account number 
// “depositMoney”, which allows putting money in the bank account using the account number

const bankAccount = {
    "bankAccountID" : "MyADB_Accnt",
    "accountNumber" : "0410010803",
    "createdAt" : "Dec 19, 2022",
    "arr_credentials" : [] 
}
    bankAccount ["arr_credentials"] =
    ["username: " + "BankoKoIto",    
    "password: " + "a1b2c3Blahblahblah",
    "pin: " + "162738",
    "debitCard: " + "Mark " + "Cruz |" + " Jan 1, 1990",
    "validID: " + "Driver's License: " + "D-20-98-166255",
    "address: " + "Block 1 Lot 8 Ruby St., Villa Aurora Homes, Brgy Loyola Heights, Quezon City", 
]

    console.log(bankAccount);

function getBankAccountDetails(name) {
        let balance = 0;
   
        function CurrentBalance() {
             console.log(`Hello ${name}, your current balance is ₱${balance}`);
        }

        function depositMoney(amount){
            balance += amount;
                 console.log(`Hello ${name}, you have deposited ₱${amount}`);
        }

        function WithdrawMoney(amount){
            if (amount > balance) {
            console.log(`Hello ${name}, you have withdrawn ₱${amount}`);
                return;
        }
            balance -= amount;
            console.log(`Hello ${name}, you have withdrawn ₱${amount}`);
        }   
             
             return {
                CurrentBalance,
                WithdrawMoney,
                depositMoney,
              };
        }
   
        const account = getBankAccountDetails(`Mark Cruz`);
   
        account.CurrentBalance();
        account.depositMoney(500);
        account.WithdrawMoney(100);
        account.CurrentBalance();
       


